name: 'ACTIONGO'
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2  
    - name: Install Salesforce CLI
      run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
          mkdir sfdx-cli
          tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
          ./sfdx-cli/install
    - name: Auth
      run: |
         echo "${secrets.SERVER}" > server.key
         cat server.key
         sfdx force:auth:jwt:grant --clientid ${{secrets.CONSUMER_KEY}}  --jwtkeyfile ./server.key -u sekar@trailhead.com  --setdefaultdevhubusername -a devhub --instanceurl https://sekartrailhead-dev-ed.my.salesforce.com
     
    - name: Create Project
      run: |
        sfdx force:project:create -n Pro -s Sekar
    - name: Create Project
      run: |
         cd Pro
         sfdx force:org:create adminEmail=gnanasekar.manoharan@email.com edition=Developer \
          username=ADMIN@Gnanasekar.com
      

   
