name: 'ACTIONGO'
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      if: github.event.action == 'opened' || github.event.action == 'synchronize'
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install Salesforce CLI
      run: |
        npm install sfdx-cli
        node_modules/sfdx-cli/bin/run --version
        node_modules/sfdx-cli/bin/run plugins --core      
    - name: Authenticate DevHub
      run: |
        echo "${SERVER}" > server.key
        node_modules/sfdx-cli/bin/run force:auth:jwt:grant --clientid ${{secrets.SALESFORCE_CONSUMER_KEY}} --jwtkeyfile server.key --username ${{secrets.SALESFORCE_DEVHUB_USERNAME}} --setdefaultdevhubusername -a devhub
      env:
        SALESFORCE_JWT_SECRET_KEY: ${{secrets.SERVER}}

    - name: Create Project
      run: |
        sfdx force:project:create -n Pro -s Sekar
    - name: ORG CREATION
      run: |
         cd Pro
         sfdx force:org:create adminEmail=gnanasekar.manoharan@email.com edition=Developer \
          username=ADMIN@Gnanasekar.com
      

   
